module.exports = {
  name: "joke",
  aliases: ["jokes"],
  run: async (client, message) => {
    const jokes = [
      "What rock group has four men that don't sing? Mount Rushmore.",
      'When I was a kid, my mother told me I could be anyone I wanted to be. Turns out, identity theft is a crime.',
      'A guy goes to his doctor because he can see into the future. The doctor asks him,"How long have you suffered from that condition?" The guy tells him, "Since next Monday."',
      'What do sprinters eat before a race? Nothing, they fast!',
      'What concert costs just 45 cents? 50 Cent featuring Nickelback!',
      "What do you call a mac 'n' cheese that gets all up in your face? Too close for comfort food!",
      "Why couldn't the bicycle stand up by itself? It was two tired!",
      'Did you hear about the restaurant on the moon? Great food, no atmosphere!',
      'How many apples grow on a tree? All of them!',
      "Did you hear the rumor about butter? Well, I'm not going to spread it!",
      'I like telling Dad jokes. Sometimes he laughs!',
      'To whoever stole my copy of Microsoft Office, I will find you. You have my Word!',
      'Q. How do you comfort a JavaScript bug? a. You console it',
      'When a JavaScript date has gone bad, "Don\'t call me, I\'ll callback you. I promise!"',
      'Dev1 saw a strange JavaScript function & asked, "What is this?". Dev2 responded, "I don\'t know. I would\'ve called you, but I was in a bind"',
      "Q. Why was the JavaScript developer sad? a. Because he didn't Node how to Express himself",
      'Q. Why did Jason cover himself with bubble wrap? a. Because he wanted to make a cross-domain JSONP request',
      "Q. Why did the CoffeeScript developer keep getting lost? a. Because he couldn't find his source without a map",
      'Q. Why did the developer go broke? a. Because he used up all his cache',
      'Q. Why did the JavaScript boxer goto the chiropractor? a. Because his backbone was angular from a knockout and required attention',
      "Today at the bank, an old lady asked me to help check her balance. So I pushed her over.",
      "The other day, my wife asked me to pass her lipstick but I accidentally passed her a glue stick. She still isn't talking to me.",
      "I couldn't figure out why the baseball kept getting larger. Then it hit me.",
      "I don't want to brag, I finished the puzzle in under a week and it said 2-4 years on the box.",
      "Why was the picture sent to jail? It was framed.",
      "Why did it take so long for the pirates to learn the Alphabet? They got stuck at C.",
      "What did the traffic light say to the car? Don’t look! I’m about to change.",
      "My boss told me to have a good day.. so I went home.",
      "I think i would like a job cleaning mirrors, it's just something I could really see myself doing.",
      "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
      "Why did the scarecrow win an award? Because he was outstanding in his field.",
      "Why did the melon jump into the lake? It wanted to be a water-melon.",
      "What did the duck say when it bought lipstick? \'Put it on my bill.\'",
      "What do you call a pig that does karate? A pork chop.",
      "What has a bed that you can’t sleep in? A river.",
      "Why were the teacher’s eyes crossed? She couldn’t control her pupils.",
      "What starts with E, ends with E, and has only 1 letter in it? An Envelope.",
      "How does the ocean say hello? It waves.",
      "What lights up a soccer stadium? A soccer match.",
      "What creature is smarter than a talking parrot? A spelling bee.",
      "Which U.S. state has the smallest soft drinks? Minnesota (as in, “mini-soda”).",
      "Why couldn’t the leopard play hide and seek? Because he was always spotted.",
      "Apparently, you can’t use “beef stew” as a password. It’s not stroganoff.",
      "Why did the drum take a nap? It was beat.",
      "Where do hamburgers go dancing?  They go to the meat-ball.",
      "Why did the tomato turn red?  It saw the salad dressing.",
      "Why shouldn’t you write with a broken pencil? Because it’s pointless.",
      "What do you call two monkeys that share an Amazon account? Prime mates.",
      "Why are teddy bears never hungry? Because they’re always stuffed!",
      "Why did the tree go to the dentist? It needed a root canal.",
      "If athletes get athlete’s foot, what do elves get? Mistle-toes.",
      "Why couldn’t the pony sing? Because she was a little hoarse.",
      "Where do cows go for entertainment? The mooooo-vies!",
      "What do you call a pig that does karate? A pork chop.",
      "How does NASA organize a party? They planet.",
      "Why did Adele cross the road?  To sing, “Hello from the other side!",
      "What runs around a yard without actually moving? A fence.",
      "What’s an astronaut’s favorite candy? A Mars bar.",
      "Where do sheep go to get their hair cut?  The baa-baa shop.",
      "Why are there gates around cemeteries? Because people are dying to get in.",
      "What do you get when you cross a snake with a pie? A pie-thon!",
      "Why is Peter Pan always flying? He neverlands.",
      "What’s the most musical part of the chicken? The drumstick.",
      "Why do seagulls fly over the sea? Because if they flew over a bay, they would be bagels.",
      "How do you know when the moon has had enough to eat? When it’s full.",
      "What kind of music do planets like? Neptunes.",
      "Why can’t you trust an atom? Because they make up everything.",
      "What do you call a group of disorganized cats? A cat-tastrophe.",
      "Why do bees have sticky hair? Because they use honeycombs.",
      "Where do you learn to make banana splits? At sundae school.",
      "How do you tell if a vampire is sick? By how much he is coffin.",
      "Why are ghosts good cheerleaders?  Because they have a lot of spirit!",
      "What happens to a frog’s car when it breaks down? It gets toad away.",
      "Why did the witches’ team lose the baseball game?  Their bats flew away.",
      "Why did the school kids eat their homework? Because their teacher told them it was a piece of cake.",
      "Why are hairdressers never late for work?  Because they know all the short cuts!",
      "What is the difference between a teacher and a train? One says, “Spit out your gum,” and the other says, \'Choo choo choo!\'",
      "Why does Humpty Dumpty love autumn?  Because Humpty Dumpty had a great fall.",
      "How do you make a tissue dance? Put a little boogie in it.",
      "What is the tallest building in the entire world?  The library, because it has so many stories.",
      "How do trees access the internet? They log in.",
      "What do you get when you cross a fish and an elephant?  Swimming trunks.",
      "Why did the painting go to jail?  It was framed.",
      "Why did Cinderella get kicked off the soccer team? Because she ran away from the ball.",
      "Why do we tell actors to break a leg?  Because every play has a cast.",
      "Helvetica and Times New Roman walk into a bar. The bartender says, \'We don’t serve your type.\'",
      "Why wouldn’t the shrimp share his treasure? Because he was a little shellfish.",
      "Why should you knock on the refrigerator before opening the door? In case there is a salad dressing",
      "When is a door not a door? When it is a jar",
      "Why should you worry about the math teacher holding graph paper?",
      "She’s definitely plotting something.",
      "Why is it sad that parallel lines have so much in common?",
      "Because they’ll never meet.",
      "Are monsters good at math?",
      "Not unless you Count Dracula.",
      "Why are obtuse angles so depressed?",
      "Because they’re never right.",
      "What’s the best way to woo a math teacher?",
      "Use acute angle.",
      "How do you stay warm in any room?",
      "Sit in the corner, where it’s always 90 degrees.",
      "Why should the number 288 never be mentioned? It’s two gross.",
      "Why was the math book sad? Because it had so many problems.",
      "Why was six scared of seven? Because seven “ate” nine.",
      "Why did the bee get married? He found his honey.",
      "Did you hear the rumor about the butter? Never mind, I shouldn’t spread it!",
      "I’m really good at sleeping. I can do it with my eyes closed.",
      "What do you call a fake noodle? An impasta",
      "Why can’t a bicycle stand on it’s own? It is two tired.",
      "What is the opposite of a croissant? A happy uncle.",
      "What does it make you if you see a robbery at an Apple Store? An iwitness.",
      "What is an astronaut’s favorite key on a keyboard? The space bar.",
      "What is brown and sticky? A stick",
      "Can February March? No but April May",
      "Son: Dad, what's an alcoholic?\nDad: Do you see those four trees? Well, an alcoholic would see 8\nSon: But Dad, there's only 2",
      "Son: Dad, what's an alcoholic?\nDad: Do you see those four trees? Well, an alcoholic would see 8\nSon: But Dad, there's only 2",
      "Name a word that begins with F, and end with UCK? - FIRETEUCK",
      "What's white and sticky, and better to spit than swallow? - TOOTHPASTE",
      "I go in hard, I come out soft, and sometimes you like to blow me. What am I? - CHEWING GUM",
    ];

    message.channel.send(jokes[Math.floor(Math.random() * jokes.length)]);
  }
}